name: pos_module
description: Workspace monorepo du module POS - Flutter, ObjectBox, Supabase
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

workspace:
  - app
  - packages/pos_core
  - packages/pos_domain
  - packages/pos_data
  - packages/pos_pos
  - packages/pos_inventory
  - packages/pos_billing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
