name: pos_data
description: Implémentations ObjectBox, Supabase et repositories concrets
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  pos_core:
    path: ../pos_core
  pos_domain:
    path: ../pos_domain
  objectbox: ^5.3.2
  objectbox_flutter_libs: ^5.3.2
  path: ^1.9.1
  path_provider: ^2.1.6
  supabase_flutter: ^2.16.0
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.3.1

dev_dependencies:
  analyzer: '>=8.1.1 <11.0.0'
  build_runner: ^2.7.1
  objectbox_generator: ^5.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
